language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t lelud007/docker-react -f Dockerfile.dev .

script:
  - docker run i-e Ci=true lelud007/docker-react npm run test
